apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::735418409761:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-40QRO6031GT8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::735418409761:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-04T06:14:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2044"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b2d2f6f4-2de0-4e78-9c94-89c567f7bd61
